INSERT INTO TEAM(TEAM_NAME,SHORT_NAME) VALUES('AC Milan','ACM');
INSERT INTO TEAM(TEAM_NAME,SHORT_NAME) VALUES('FC Barcelona','FCB');
INSERT INTO TEAM(TEAM_NAME,SHORT_NAME) VALUES('Borussia Dortmund','BOR');
INSERT INTO TEAM(TEAM_NAME,SHORT_NAME) VALUES('Juventus','JUV');
INSERT INTO TEAM(TEAM_NAME,SHORT_NAME) VALUES('Paris Saint-Germain','PSG');
INSERT INTO TEAM(TEAM_NAME,SHORT_NAME) VALUES('Spartak Moscow','SPA');
INSERT INTO TEAM(TEAM_NAME,SHORT_NAME) VALUES('Lyon','LYO');