INSERT INTO REFEREE(REFEREE_NAME,MATCH_CONTROLLED) VALUES ('A Marriner',30);
INSERT INTO REFEREE(REFEREE_NAME,MATCH_CONTROLLED) VALUES ('K Friend',17);
INSERT INTO REFEREE(REFEREE_NAME,MATCH_CONTROLLED) VALUES ('M Dean',65);
INSERT INTO REFEREE(REFEREE_NAME,MATCH_CONTROLLED) VALUES ('C Kavanagh',23);
INSERT INTO REFEREE(REFEREE_NAME,MATCH_CONTROLLED) VALUES ('M Atkinson',42);
