--1st match ...home_id = 2 & away_id = 4
INSERT INTO SCORES(GOALS,ASSIST,SCORING_ID,MATCH_ID,TEAM_ID) VALUES(1,0,11,1,2);
INSERT INTO SCORES(GOALS,ASSIST,SCORING_ID,ASSIST_ID,MATCH_ID,TEAM_ID) VALUES(2,1,9,11,1,2);

INSERT INTO SCORES(GOALS,ASSIST,SCORING_ID,ASSIST_ID,MATCH_ID,TEAM_ID) VALUES(1,1,23,22,1,4);

--2 match ...home_id = 2 & away_id = 2
INSERT INTO SCORES(GOALS,ASSIST,SCORING_ID,MATCH_ID,TEAM_ID) VALUES(1,0,17,2,3);
INSERT INTO SCORES(GOALS,ASSIST,SCORING_ID,MATCH_ID,TEAM_ID) VALUES(1,0,18,2,3);

INSERT INTO SCORES(GOALS,ASSIST,SCORING_ID,ASSIST_ID,MATCH_ID,TEAM_ID) VALUES(1,1,3,2,2,1);
INSERT INTO SCORES(GOALS,ASSIST,SCORING_ID,ASSIST_ID,MATCH_ID,TEAM_ID) VALUES(1,1,4,3,2,1);

--3st match ...home_id = 2 & away_id =3
INSERT INTO SCORES(GOALS,ASSIST,SCORING_ID,ASSIST_ID,MATCH_ID,TEAM_ID) VALUES(2,1,22,20,3,4);

INSERT INTO SCORES(GOALS,ASSIST,SCORING_ID,MATCH_ID,TEAM_ID) VALUES(1,0,3,3,1);
INSERT INTO SCORES(GOALS,ASSIST,SCORING_ID,MATCH_ID,TEAM_ID) VALUES(1,0,4,3,1);
INSERT INTO SCORES(GOALS,ASSIST,SCORING_ID,ASSIST_ID,MATCH_ID,TEAM_ID) VALUES(1,1,5,2,3,1);

--4st match ...home_id = 3 & away_id = 4
INSERT INTO SCORES(GOALS,ASSIST,SCORING_ID,MATCH_ID,TEAM_ID) VALUES(1,0,3,4,1);
INSERT INTO SCORES(GOALS,ASSIST,SCORING_ID,ASSIST_ID,MATCH_ID,TEAM_ID) VALUES(1,1,2,4,4,1);
INSERT INTO SCORES(GOALS,ASSIST,SCORING_ID,ASSIST_ID,MATCH_ID,TEAM_ID) VALUES(1,1,4,5,4,1);

INSERT INTO SCORES(GOALS,ASSIST,SCORING_ID,ASSIST_ID,MATCH_ID,TEAM_ID) VALUES(2,1,40,41,4,7);
INSERT INTO SCORES(GOALS,ASSIST,SCORING_ID,MATCH_ID,TEAM_ID) VALUES(1,0,40,4,7);
INSERT INTO SCORES(GOALS,ASSIST,SCORING_ID,MATCH_ID,TEAM_ID) VALUES(1,0,39,4,7);

--5st match ...home_id = 2 & away_id = 0
INSERT INTO SCORES(GOALS,ASSIST,SCORING_ID,MATCH_ID,TEAM_ID) VALUES(1,0,41,5,7);
INSERT INTO SCORES(GOALS,ASSIST,SCORING_ID,ASSIST_ID,MATCH_ID,TEAM_ID) VALUES(1,1,40,41,5,7);
--no means ...0 away goal--

--6st match ...home_id = 1 & away_id = 3
INSERT INTO SCORES(GOALS,ASSIST,SCORING_ID,MATCH_ID,TEAM_ID) VALUES(1,0,22,6,4);

INSERT INTO SCORES(GOALS,ASSIST,SCORING_ID,ASSIST_ID,MATCH_ID,TEAM_ID) VALUES(1,1,4,2,6,1);
INSERT INTO SCORES(GOALS,ASSIST,SCORING_ID,MATCH_ID,TEAM_ID) VALUES(1,0,2,6,1);
INSERT INTO SCORES(GOALS,ASSIST,SCORING_ID,ASSIST_ID,MATCH_ID,TEAM_ID) VALUES(1,1,4,3,6,1);

--7st match ...home_id = 2 & away_id = 1
INSERT INTO SCORES(GOALS,ASSIST,SCORING_ID,MATCH_ID,TEAM_ID) VALUES(1,0,21,7,4);
INSERT INTO SCORES(GOALS,ASSIST,SCORING_ID,MATCH_ID,TEAM_ID) VALUES(1,0,23,7,4);

INSERT INTO SCORES(GOALS,ASSIST,SCORING_ID,ASSIST_ID,MATCH_ID,TEAM_ID) VALUES(1,1,2,5,7,1);
