INSERT INTO STADIUM(STADIUM_NAME,CAPACITY) VALUES('San Siro',80018);
INSERT INTO STADIUM(STADIUM_NAME,CAPACITY) VALUES('Westfalenstadion',81365);
INSERT INTO STADIUM(STADIUM_NAME,CAPACITY) VALUES('Groupama Stadium',59186);
INSERT INTO STADIUM(STADIUM_NAME,CAPACITY) VALUES('Parc des Princes',48527);
INSERT INTO STADIUM(STADIUM_NAME,CAPACITY) VALUES('Johan Cruyff Arena',54033);
INSERT INTO STADIUM(STADIUM_NAME,CAPACITY) VALUES('Otkritie Arena',45360);